language: objective-c
osx_image: xcode8.3
rvm:
- 2.2
before_install:
- chmod a+x ./TravisCI/Scripts/install.sh
- chmod a+x ./TravisCI/Scripts/build.sh
- chmod a+x ./TravisCI/Scripts/unitTests.sh
- chmod a+x ./TravisCI/Scripts/compressBuilds.sh
install:
- ./Scripts/install.sh
before_scripts:
- ./Scripts/unitTests.sh
script:
- ./Scripts/build.sh
after_script:
- ./Scripts/compressBuilds.sh

# blocklist
branches:
  except:
  - legacy
  - experimental

# safelist
branches:
  only:
  - master
  - production