language: objective-c
osx_image: xcode8.3
rvm:
- 2.2
before_install:
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
- chmod a+x ./Scripts/unitTests.sh
- chmod a+x ./Scripts/compressBuilds.sh
install:
- ./Scripts/install.sh
before_scripts:
- ./Scripts/unitTests.sh
script:
- ./Scripts/build.sh
after_script:
- ./Scripts/compressBuilds.sh